# Generated by Django 2.2.10 on 2021-04-03 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestBale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bale_ID', models.CharField(max_length=255)),
                ('Staple_length', models.CharField(max_length=255)),
                ('Trash', models.CharField(max_length=255)),
                ('Bundle_Strength', models.CharField(max_length=255)),
                ('Micronaire', models.CharField(max_length=255)),
                ('Rd', models.CharField(max_length=255)),
                ('b', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Bale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bale_ID', models.CharField(max_length=255)),
                ('Lot_ID', models.CharField(max_length=255)),
                ('Station', models.CharField(max_length=255)),
                ('Crop_Year', models.CharField(max_length=255)),
                ('Pick', models.CharField(max_length=255)),
                ('Staple_Type', models.CharField(max_length=255)),
                ('Staple_length', models.CharField(max_length=255)),
                ('Trash', models.CharField(max_length=255)),
                ('Bundle_Strength', models.CharField(max_length=255)),
                ('Micronaire', models.CharField(max_length=255)),
                ('Moisture', models.CharField(max_length=255)),
                ('Asking_Price', models.CharField(max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
