# Generated by Django 2.2.10 on 2021-06-15 04:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_bale_ginnerid'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bale',
            unique_together={('Lot_ID', 'Bale_ID', 'Station', 'user', 'ginnerid')},
        ),
    ]
