# Generated by Django 2.2.10 on 2021-06-17 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_auto_20210615_0427'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeeksBidsToSupply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberofbales', models.CharField(max_length=255)),
                ('dateofdelivery', models.DateField()),
                ('Station', models.CharField(max_length=255)),
                ('StapleLength', models.CharField(max_length=255)),
                ('MaxStapleLength', models.CharField(max_length=255)),
                ('Trash', models.CharField(max_length=255)),
                ('BundleStrength', models.CharField(max_length=255)),
                ('Rd', models.CharField(max_length=255)),
                ('bdata', models.CharField(max_length=255)),
                ('Organic', models.BooleanField(default=False)),
                ('BCI', models.BooleanField(default=False)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('pincode', models.CharField(max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuctionMyBales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=255)),
                ('startingprice', models.CharField(max_length=255)),
                ('auctionduration', models.DateField(blank=True, null=True)),
                ('paymentterms', models.CharField(max_length=255)),
                ('auction', models.BooleanField(default=False)),
                ('bales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Bale')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
