# Generated by Django 2.2.10 on 2021-06-21 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auctionmybales_seeksbidstosupply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testbale',
            name='Bale_ID',
        ),
    ]
